<?php
add_action( 'init', 'githubauthvideo_register_post_type' );
function githubauthvideo_register_post_type() {
	$args = [
		'label'  => esc_html__( 'Github Sponsor Videos', 'text-domain' ),
		'labels' => [
			'menu_name'          => esc_html__( 'Github Sponsor Videos', 'githubauthvideo' ),
			'name_admin_bar'     => esc_html__( 'Github Sponsor Video', 'githubauthvideo' ),
			'add_new'            => esc_html__( 'Add Github Sponsor Video', 'githubauthvideo' ),
			'add_new_item'       => esc_html__( 'Add new Github Sponsor Video', 'githubauthvideo' ),
			'new_item'           => esc_html__( 'New Github Sponsor Video', 'githubauthvideo' ),
			'edit_item'          => esc_html__( 'Edit Github Sponsor Video', 'githubauthvideo' ),
			'view_item'          => esc_html__( 'View Github Sponsor Video', 'githubauthvideo' ),
			'update_item'        => esc_html__( 'View Github Sponsor Video', 'githubauthvideo' ),
			'all_items'          => esc_html__( 'All Github Sponsor Videos', 'githubauthvideo' ),
			'search_items'       => esc_html__( 'Search Github Sponsor Videos', 'githubauthvideo' ),
			'parent_item_colon'  => esc_html__( 'Parent Github Sponsor Video', 'githubauthvideo' ),
			'not_found'          => esc_html__( 'No Github Sponsor Videos found', 'githubauthvideo' ),
			'not_found_in_trash' => esc_html__( 'No Github Sponsor Videos found in Trash', 'githubauthvideo' ),
			'name'               => esc_html__( 'Github Sponsor Videos', 'githubauthvideo' ),
			'singular_name'      => esc_html__( 'Github Sponsor Video', 'githubauthvideo' ),
		],
		'public'              => false,
		'exclude_from_search' => true,
		'publicly_queryable'  => false,
		'show_ui'             => true,
		'show_in_nav_menus'   => false,
		'show_in_admin_bar'   => true,
		'show_in_rest'        => true,
		'capability_type'     => 'post',
		'hierarchical'        => false,
		'has_archive'         => true,
		'query_var'           => false,
		'can_export'          => true,
		'rewrite_no_front'    => false,
		'show_in_menu'        => 'upload.php',
		'menu_icon'           => 'dashicons-video-alt2',
		'supports' => [
			'title',
			'revisions',
			'custom_fields'
		],
		'rewrite' => true
	];

	register_post_type( 'github-sponsor-video', $args );
}

    // add the filter 
	add_filter( 'manage_posts_columns', 'githubauthvideo_add_id_column', 2, 2 ); 
	add_action( 'manage_posts_custom_column', 'githubauthvideo_add_id_column_content', 2, 2 );
	
    // define the manage_posts_columns callback 
    function githubauthvideo_add_id_column( $posts_columns, $post_type ) { 
		if($post_type == 'github-sponsor-video') {
			$post_columns['githubauthvideo_id'] = 'ID';
		}
        return $posts_columns; 
	}; 
	
	function githubauthvideo_add_id_column_content ( $column, $id ) {
		if('githubauthvideo_id' == $column) {
			echo $id;
		}
	}

/**
 * Generated by the WordPress Meta Box Generator
 * https://jeremyhixon.com/tool/wordpress-meta-box-generator/
 * 
 * Retrieving the values:
 * Video Location URI = get_post_meta( get_the_ID(), 'githubauthvideo_video-location-uri', true )
 * Github Organization ID = get_post_meta( get_the_ID(), 'githubauthvideo_github-organization-id', true )
 * Github Sponsorship Tier ID = get_post_meta( get_the_ID(), 'githubauthvideo_github-sponsorship-tier-id', true )
 * Splash Screen = get_post_meta( get_the_ID(), 'githubauthvideo_splash-screen', true )
 */
class Github_Video_Entry_Fields {
	private $config = '{"title":"Video Entry Data","description":"Specifies the necessary mapping to Github Sponsor Auth videos.","prefix":"githubauthvideo_","domain":"githubauthvideo","class_name":"Github_Video_Entry_Fields","post-type":["github-sponsor-video"],"context":"normal","priority":"default","cpt":"github-sponsor-video","fields":[{"type":"url","label":"Video Location URI","id":"githubauthvideo_video-location-uri"},{"type":"text","label":"Github Organization ID","id":"githubauthvideo_github-organization-id"},{"type":"text","label":"Github Sponsorship Tier ID","default":"*","id":"githubauthvideo_github-sponsorship-tier-id"},{"type":"media","label":"Splash Screen","return":"url","id":"githubauthvideo_splash-screen"}]}';

	public function __construct() {
		$this->config = json_decode( $this->config, true );
		$this->process_cpts();
		add_action( 'add_meta_boxes', [ $this, 'add_meta_boxes' ] );
		add_action( 'admin_enqueue_scripts', [ $this, 'admin_enqueue_scripts' ] );
		add_action( 'admin_head', [ $this, 'admin_head' ] );
		add_action( 'save_post', [ $this, 'save_post' ] );
	}

	public function process_cpts() {
		if ( !empty( $this->config['cpt'] ) ) {
			if ( empty( $this->config['post-type'] ) ) {
				$this->config['post-type'] = [];
			}
			$parts = explode( ',', $this->config['cpt'] );
			$parts = array_map( 'trim', $parts );
			$this->config['post-type'] = array_merge( $this->config['post-type'], $parts );
		}
	}

	public function add_meta_boxes() {
		foreach ( $this->config['post-type'] as $screen ) {
			add_meta_box(
				sanitize_title( $this->config['title'] ),
				$this->config['title'],
				[ $this, 'add_meta_box_callback' ],
				$screen,
				$this->config['context'],
				$this->config['priority']
			);
		}
	}

	public function admin_enqueue_scripts() {
		global $typenow;
		if ( in_array( $typenow, $this->config['post-type'] ) ) {
			wp_enqueue_media();
		}
	}

	public function admin_head() {
		global $typenow;
		if ( in_array( $typenow, $this->config['post-type'] ) ) {
			?><script>
				jQuery.noConflict();
				(function($) {
					$(function() {
						$('body').on('click', '.rwp-media-toggle', function(e) {
							e.preventDefault();
							let button = $(this);
							let rwpMediaUploader = null;
							rwpMediaUploader = wp.media({
								title: button.data('modal-title'),
								button: {
									text: button.data('modal-button')
								},
								multiple: true
							}).on('select', function() {
								let attachment = rwpMediaUploader.state().get('selection').first().toJSON();
								button.prev().val(attachment[button.data('return')]);
							}).open();
						});
					});
				})(jQuery);
			</script><?php
			?><?php
		}
	}

	public function save_post( $post_id ) {
		foreach ( $this->config['fields'] as $field ) {
			switch ( $field['type'] ) {
				case 'url':
					if ( isset( $_POST[ $field['id'] ] ) ) {
						$sanitized = esc_url_raw( $_POST[ $field['id'] ] );
						update_post_meta( $post_id, $field['id'], $sanitized );
					}
					break;
				default:
					if ( isset( $_POST[ $field['id'] ] ) ) {
						$sanitized = sanitize_text_field( $_POST[ $field['id'] ] );
						update_post_meta( $post_id, $field['id'], $sanitized );
					}
			}
		}
	}

	public function add_meta_box_callback() {
		echo '<div class="rwp-description">' . $this->config['description'] . '</div>';
		$this->fields_table();
	}

	private function fields_table() {
		?><table class="form-table" role="presentation">
			<tbody><?php
				foreach ( $this->config['fields'] as $field ) {
					?><tr>
						<th scope="row"><?php $this->label( $field ); ?></th>
						<td><?php $this->field( $field ); ?></td>
					</tr><?php
				}
			?></tbody>
		</table><?php
	}

	private function label( $field ) {
		switch ( $field['type'] ) {
			case 'media':
				printf(
					'<label class="" for="%s_button">%s</label>',
					$field['id'], $field['label']
				);
				break;
			default:
				printf(
					'<label class="" for="%s">%s</label>',
					$field['id'], $field['label']
				);
		}
	}

	private function field( $field ) {
		switch ( $field['type'] ) {
			case 'media':
				$this->input( $field );
				$this->media_button( $field );
				break;
			default:
				$this->input( $field );
		}
	}

	private function input( $field ) {
		if ( $field['type'] === 'media' ) {
			$field['type'] = 'text';
		}
		printf(
			'<input class="regular-text %s" id="%s" name="%s" %s type="%s" value="%s">',
			isset( $field['class'] ) ? $field['class'] : '',
			$field['id'], $field['id'],
			isset( $field['pattern'] ) ? "pattern='{$field['pattern']}'" : '',
			$field['type'],
			$this->value( $field )
		);
	}

	private function media_button( $field ) {
		printf(
			' <button class="button rwp-media-toggle" data-modal-button="%s" data-modal-title="%s" data-return="%s" id="%s_button" name="%s_button" type="button">%s</button>',
			isset( $field['modal-button'] ) ? $field['modal-button'] : __( 'Select this file', 'githubauthvideo' ),
			isset( $field['modal-title'] ) ? $field['modal-title'] : __( 'Choose a file', 'githubauthvideo' ),
			$field['return'],
			$field['id'], $field['id'],
			isset( $field['button-text'] ) ? $field['button-text'] : __( 'Upload or Select', 'githubauthvideo' )
		);
	}

	private function value( $field ) {
		global $post;
		if ( metadata_exists( 'post', $post->ID, $field['id'] ) ) {
			$value = get_post_meta( $post->ID, $field['id'], true );
		} else if ( isset( $field['default'] ) ) {
			$value = $field['default'];
		} else {
			return '';
		}
		return str_replace( '\u0027', "'", $value );
	}

}
new Github_Video_Entry_Fields;
?>